name: Node.js CI

on:
  push:
    branches: [ dev ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i -g ts-node typescript
      - run: npm install
      - run: npm ci
      # - run: npx prisma generate dev
      - run: npm test